name: Manual Release Artifacts

on: workflow_dispatch

defaults:
  run:
    shell: bash

jobs:
  release-artifact:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Install aws cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: "2"

      - name: Bundle & Upload Artifacts
        run: |
          ./scripts/bundle_seid.sh
          ./scripts/upload_seid.sh